name: init
description: Initialize bitrise __config (bitrise.yml)__ and __secrets (.bitrise.secrets.yml)__
  based on your project.
executable:
  osx: https://github.com/bitrise-core/bitrise-plugins-init/releases/download/1.0.9/bitrise-plugins-init-Darwin-x86_64
  linux: https://github.com/bitrise-core/bitrise-plugins-init/releases/download/1.0.9/bitrise-plugins-init-Linux-x86_64
trigger: ""
requirements:
- tool: bitrise
  min_version: 1.3.0
  max_version: ""
