[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/bitrise-core/bitrise-init"
  version = "1.8.0"

[[constraint]]
  name = "github.com/bitrise-io/bitrise"
  version = "1.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/envman"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
